name: calculate
version: 1.0.1
author: Abner <0x23fd5097@gmail.com>
description: >
  This project enable to make computations on decimal numbers without loosing precision like double operations.
homepage: https://github.com/noteScript/dart-calculate
environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  pedantic: ^1.11.1
dependencies: 
  decimal: ^2.3.3
