name: 发布到 pub.dev

on:
    push: # 当 push 到 main 分支，或者创建以 v 开头的 tag 时触发
      paths-ignore: # 忽略触发工作流的文件
        - 'README.md'
      branches:
        - main # 推送更改到 main 分支时触发
      tags:
        - v* # 创建以 v 开头的 tag 时触发

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 环境切换
        uses: actions/checkout@main
      - name: 自动发布
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}